version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-your_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tododb}
      MYSQL_USER: ${MYSQL_USER:-todouser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-todopass}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - todo-network

  todoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=${MYSQL_DATABASE:-tododb};User=${MYSQL_USER:-todouser};Password=${MYSQL_PASSWORD:-todopass};
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge